### ISSUE TITLE
Docker build failing 

### ISSUE THREAD

**Issue by bledMS82** [fullhunt/log4j-scan#104]
sudo docker build -t log4j-scan .
Sending build context to Docker daemon  149.5kB
Step 1/7 : FROM python:3-alpine
Head "https://registry-1.docker.io/v2/library/python/manifests/3-alpine": unauthorized: incorrect username or password

I verified docker hub login creds and I am using username not username@email , I verified I am able to pull other images such as hello-world 

 docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
Digest: sha256:2498fce14358aa50ead0cc6c19990fc6ff866ce72aeb5546e1d59caac3d0d60f
Status: Image is up to date for hello-world:latest
docker.io/library/hello-world:latest

**Comment by mazen160** [comment]
There seems to be an issue on the Dockerhub setup on your side. Can you please remove all the `.docker/config.json` for docker on your home directory and try to re-run the setup again?

Feel free to try it, hopefully it should work!
