### ISSUE TITLE
Sites without http https

### ISSUE THREAD

**Issue by Karmakstylez** [fullhunt/log4j-scan#107]
I want to use commands like this:
`log4j-scan --headers-file /opt/log4j-scan/headers.txt -u helloworld.org`
or
`log4j-scan --headers-file /opt/log4j-scan/headers.txt -u www.helloworld.org`

But I get an EXCEPTION error: EXCEPTION: Invalid URL 'helloworld.org': No schema supplied. Perhaps you meant http://helloworld.org?

Can this be fixed?

**Comment by mazen160** [comment]
Hi @Karmakstylez,

The tool relies on the full URL you're sending. You should be provide a valid URL instead of a hostname.
