### ISSUE TITLE
Sending POST data?

### ISSUE THREAD

**Issue by 007divyachawla** [fullhunt/log4j-scan#12]
How can we send the POST data using these tool.

**Comment by Radv1la** [comment]
python3 log4j-scan.py --request-type POST -u example.com

**Comment by 007divyachawla** [comment]
hello @Radv1la  what about the POST data parameters such as username and password

**Comment by mazen160** [comment]
@007divyachawla It's already there by default for common parameters that can be fuzzed in a single request:
https://github.com/fullhunt/log4j-scan/blob/master/log4j-scan.py#L50
