### ISSUE TITLE
Pycrypto issue

### ISSUE THREAD

**Issue by tersor** [fullhunt/log4j-scan#17]
The requirements.txt suggest installing pycrypto, which results in the following error when performing a scan:

```
AttributeError: module 'time' has no attribute 'clock'
```

According to [this issue](https://github.com/pycrypto/pycrypto/issues/173) pycrypto is dead. I solved the issue by installing a fork:

```
pip3 uninstall pycrypto
pip3 install -U pycryptodome
```

**Comment by sidh104** [comment]
pip install pycryptodome==3.4.3 

should solve the issue.

**Comment by mazen160** [comment]
Thanks @sidh104! :) I merge them into a single discussion thread
