### ISSUE TITLE
Needs parameters support

### ISSUE THREAD

**Issue by jakre1234** [fullhunt/log4j-scan#20]
Yesterday only I found potential injection via comment field, so need to implement parameter part as well. Something like fluff where in FUZZ word will be replaced by Payload in request.

**Comment by mazen160** [comment]
It's already supported for most common parameters, so that it can be tested in a single request:
https://github.com/fullhunt/log4j-scan/blob/master/log4j-scan.py#L50
Feel free to add the paramter you found to it in a PR!
