### ISSUE TITLE
Custom DNS Callback Host is not returning results

### ISSUE THREAD

**Issue by PhoenixC46** [fullhunt/log4j-scan#21]
The callback URL is being added to the query when running but no results are appearing in the web-app, does it need to be wrapped in brackets or quotes?

**Comment by mazen160** [comment]
The custom dns callback host depends on your setup, you should be able to access the DNS logs and see if you have received a DNS query for target in place. Burp Suite Collaborator Client should be helpful and intuitive for this test

**Comment by PhoenixC46** [comment]
Sorry maybe i didn't explain the issue, i've added the customer-dns-callback-host 1234abdc.interactsh.com to the command and it has no problem looking up interactsh.com but when i click the refresh button on the hosted web-app to see the results nothing appears.
I've tried to setup an in-house interactsh server but i'm not familiar with "go" and it doesn't seem to be placing files into the correct paths so nothing runs.
I'm stuck either way and can't find any documentation or articles to guide me through the process.
