### ISSUE TITLE
Crypto module problem

### ISSUE THREAD

**Issue by Sajjad-Taghinezhad** [fullhunt/log4j-scan#23]
i first run ` pip3 install -r requirements.txt`
when running the script I got this error

File "/Users/***/Tools/log4j-scan/log4j-scan.py", line 22, in <module>
    from Crypto.Cipher import AES, PKCS1_OAEP
ModuleNotFoundError: No module named 'Crypto'

any solution?

**Comment by alfrede** [comment]
i have got the same and  python3-cryptography is installed.

**Comment by Sajjad-Taghinezhad** [comment]
didn't work for me

**Comment by raphaunix** [comment]
Hi, do you have the same problem when using virtualenv?
```bash
git clone https://github.com/fullhunt/log4j-scan.git
cd log4j-scan
python3 -m venv .
source bin/activate
pip install -r requirements.txt
```

**Comment by alfrede** [comment]
have you got installed the python-cryptography package?  https://pkg.kali.org/pkg/python-cryptography

**Comment by mazen160** [comment]
Please check: https://github.com/fullhunt/log4j-scan/issues/10#issuecomment-993304115
