### ISSUE TITLE
Line 122 Invalid Syntax

### ISSUE THREAD

**Issue by ethergloo** [fullhunt/log4j-scan#27]
~/log4j-scan$ python3 log4j-scan.py -u https://log4j.lab.secbot.local
  File "log4j-scan.py", line 122
    fuzzing_headers["Referer"] = f'https://{fuzzing_headers["Referer"]}'
SyntaxError: invalid syntax

**Comment by mazen160** [comment]
It's maybe related to running the tool in Python2 since this syntax is not acceptable. Please try it in Python3 as Python2 is not supported.

**Comment by kecskemethy** [comment]
jfyi as f-strings feature was introduced in Python 3.6, any version below might produce the same... e.g. 3.5 in Debian old-stable etc... 
not just Python2 but older version of Python3 as well...

ref. https://realpython.com/python-f-strings/
