### ISSUE TITLE
IP's

### ISSUE THREAD

**Issue by lesleycooks** [fullhunt/log4j-scan#28]
Can this be run against IP's and ports ?

**Comment by zsolt-halo** [comment]
Yes, but the tool requires you to have a protocol in front of the ip/port so this will not work

`localhost:8080` but `http://localhost:8080` and `https://localhost:8080` will do

You can use a tool called `httpx` to generate a huge list of domains together with their protocols out of a list of protocol-less txt file.

**Comment by mazen160** [comment]
Yes! it's possible as @zsolt-halo mentioned :)
