### ISSUE TITLE
OS X error module Crypto

### ISSUE THREAD

**Issue by ak1t4** [fullhunt/log4j-scan#3]
python3 log4j-scan.py  -h
Traceback (most recent call last):
  File "log4j-scan.py", line 22, in <module>
    from Crypto.Cipher import AES, PKCS1_OAEP
ModuleNotFoundError: No module named 'Crypto'

**Comment by ak1t4** [comment]
was solved with :

pip3 install pycryptodome

now works!

**Comment by mazen160** [comment]
@ak1t4 Thanks! I just updated requirements.txt file with `pycrypto`
