### ISSUE TITLE
Covert wait_time to integer 

### ISSUE THREAD

**Issue by KINGSABRI** [fullhunt/log4j-scan#51]
In the following line, `sleep()` is expecting an Integer while the user input `--wait-time` will be a string 
https://github.com/fullhunt/log4j-scan/blob/7be0f1c02ce3494469dc73a177e6f0c96f0016d9/log4j-scan.py#L337

This causes the following exception
```
Traceback (most recent call last):
  File "/home/KING/Code/Python/log4j-scan/log4j-scan.py", line 336, in <module>
    main()
  File "/home/KING/Code/Python/log4j-scan/log4j-scan.py", line 324, in main
    time.sleep(args.wait_time)
TypeError: an integer is required (got type str)
```

- Solution
```python
time.sleep(int(args.wait_time))
```

**Comment by mazen160** [comment]
@KINGSABRI Just pushed a fix now, thank you!! :)
https://github.com/fullhunt/log4j-scan/commit/5607ee6d0831af59f2c79b6cb6ea23427916dcc9
