### ISSUE TITLE
Error on a first run

### ISSUE THREAD

**Issue by YanDatsiuk** [fullhunt/log4j-scan#52]
When you run command:
`python3 log4j-scan.py -h`

you get the error message: 
`
File "log4j-scan.py", line 132
 fuzzing_headers["Referer"] = f'https://{fuzzing_headers["Referer"]}'
`

**Comment by freeloaderxoxo** [comment]
I too received the error, on first run. but on different lines. 

Mac-M1CTG3QD:log4j-scan milin$ python3 log4j-scan.py -u https://google.com
Traceback (most recent call last):
  File "/Users/milin/log4j-scan/log4j-scan.py", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by trietphm** [comment]
@YanDatsiuk Look like the script is compatible with [Python >= 3.6](https://stackoverflow.com/questions/42126794/getting-an-invalid-syntax-when-trying-to-perform-string-interpolation). Got the same error syntax when running on my Python 3.5, but it works fine in Python 3.8
@freeloaderxoxo you need to install the required library as well. Use these commands:
```
pip3 install -U pycryptodome
pip3 install  -r requirements.txt
```

**Comment by freeloaderxoxo** [comment]
Thanks, I reinstalled everything and installed the requirements again . solved my issue.

**Comment by YanDatsiuk** [comment]
Just make sure that you are running updated python interpreter.
