### ISSUE TITLE
HTTPS？HTTP！

### ISSUE THREAD

**Issue by wosk0x01** [fullhunt/log4j-scan#6]
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='interactsh.com', port=443): Read timed out. (read timeout=30)

u connect to 443 port, but the server is http://interactsh.com/, http server has only 80 port open, the 443 will not work, it better to fix

**Comment by mazen160** [comment]
Hi @wosk0x01 
It's working on 443, but due to massive amount of usage at the moment, interact may have an outage at the moment.

**Comment by ak1t4** [comment]
Hey man! awesome tool, I have the same issue, 

maybe an option to set our own callback server? like collaborator? 

cheers!

**Comment by ak1t4** [comment]
we can choose the ins callback provider

python3 log4j-scan.py -l list.urls --dns-callback-provider dnslog.cn

will be great add canary tokens here :)

congrats for the tool, is quite awesome :)
