### ISSUE TITLE
EXCEPTION: [Errno 2] No such file or directory: 'headers.txt'

### ISSUE THREAD

**Issue by solik00** [fullhunt/log4j-scan#61]
EXCEPTION: [Errno 2] No such file or directory: 'headers.txt' during scan

**Comment by xoiga123** [comment]
Remember to clone `headers.txt` and `headers-large.txt` too.

**Comment by mazen160** [comment]
@solik00 As @xoiga123, please clone the entire repository, and then you will have headers file too. You can also specify headers file path by:
```
  --headers-file HEADERS_FILE
                        Headers fuzzing list - [default: headers.txt].
```
