### ISSUE TITLE
[EXCEPTIONS] ConnectionError

### ISSUE THREAD

**Issue by sokobban** [fullhunt/log4j-scan#68]
Hello,
I'm facing this issue can anybody help me with this?

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='interact.sh', port=443): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faa56dd0c18>: Failed to establish a new connection: [Errno 111] Connection refused',))`

**Comment by Westbrookadmin** [comment]
@sokobban 
This problem is because you opened the agent, the system agent can be closed.

**Comment by sokobban** [comment]
> @sokobban This problem is because you opened the agent, the system agent can be closed.

Hello,
Thank you for the answer.
Could you be more specific which agent I open....
Thanks in advance

**Comment by AnthoBalitrand** [comment]
Are you using proxies ? Or are there any firewall with URL filtering enabled which could RST the connection ? (interact.sh can be classified as a threat by a lot of URL categorization services).

**Comment by Westbrookadmin** [comment]
> > @sokobban This problem is because you opened the agent, the system agent can be closed.
> 
> Hello, Thank you for the answer. Could you be more specific which agent I open.... Thanks in advance

You can check the proxy Settings of the system.

**Comment by mazen160** [comment]
This is either because the DNS callback provider is down, or you are unable to connect to it due to network issue that you have.

**Comment by daniel-capp** [comment]
@mazen160  I'm encountering this same issue. What network issue would cause this?
