### ISSUE TITLE
Unclear interpretation of Scan Results

### ISSUE THREAD

**Issue by roger-wilco-66** [fullhunt/log4j-scan#71]
Hi,

first, thank you for sharing this tool, it is very helpful.
However, we have an issue with the interpretation of the scan result of log4j-scan.    Upon pointing it to a known vulnerable test system, it delivers consistent results.   We observe, that the remote address in the output is equal to the ip address of the system which is being tested.
We now found an anomaly scanning live systems.  The scan results are positive, but the remote address points to internet ip's which are totally unrelated to the live system.   They point largely to google-cloud servers or WoodyNet IPs.  Is this an indicator of compromise or just an anomaly?  We can't pinpoint where that exactly comes from.  Obviously it has something to do with interactsh, but it is unclear at which point the external IPs are fed in.  Here's a snippet of the output (target IP and token obfuscated, obviously):

{'timestamp': '2021-12-14T11:00:02.489479218Z', 'host': 'xxx.xxx.xxx.xxx.[token].interact.sh', 'remote_address': '66.185.120.243'}
{'timestamp': '2021-12-14T11:00:02.664853784Z', 'host': 'xxx.xxx.xxx.xxx.[token].interact.sh', 'remote_address': '66.185.120.243'}
{'timestamp': '2021-12-14T11:00:02.843801487Z', 'host': 'xxx.xxx.xxx.xxx.[token].interact.sh', 'remote_address': '66.185.120.243'}
{'timestamp': '2021-12-14T11:00:03.020504231Z', 'host': 'xxx.xxx.xxx.xxx.[token].interact.sh', 'remote_address': '66.185.120.243'}
{'timestamp': '2021-12-14T11:00:03.198737042Z', 'host': 'xxx.xxx.xxx.xxx.[token].interact.sh', 'remote_address': '66.185.120.243'}
{'timestamp': '2021-12-14T11:00:06.71736305Z', 'host': 'xxx.xxx.xxx.xxx.[token].interact.sh', 'remote_address': '172.253.10.195'}
{'timestamp': '2021-12-14T11:00:06.719712788Z', 'host': 'xxx.xxx.xxx.xxx.[token].interact.sh', 'remote_address': '172.253.10.196'}
{'timestamp': '2021-12-14T11:00:06.731693918Z', 'host': 'xxx.xxx.xxx.xxx.[token].interact.sh', 'remote_address': '66.185.120.243'}
{'timestamp': '2021-12-14T11:00:06.91019229Z', 'host': 'xxx.xxx.xxx.xxx.[token].interact.sh', 'remote_address': '66.185.120.243'}
{'timestamp': '2021-12-14T11:00:07.08665417Z', 'host': 'xxx.xxx.xxx.xxx.[token].interact.sh', 'remote_address': '66.185.120.243'}  

Any thoughts on this?  Has this also been observed by others, maybe?

ty  
Roger

**Comment by mazen160** [comment]
Hi @roger-wilco-66,
Thank you very much for the detailed explanation.

The `remote_address` on all cases will be the DNS server that was seen to be generating the DNS query. If you send

```
dig A sample.token.interact.sh @8.8.8.8
```
you would see that the remote address is coming from Google servers.

It maybe that the systems resolvers are using a resolver that is forwarding queries to these IPs. It should not be a reliable way to pin-point vulnerable systems.

The most reliable way is testing the remote address (or host) in the prefix of the DNS callback: this can lead to the vulnerable system.

All the best!
- Mazin
