### ISSUE TITLE
SyntaxError: invalid syntax 

### ISSUE THREAD

**Issue by tonoitp** [fullhunt/log4j-scan#79]
File "log4j-scan.py", line 136
    fuzzing_headers["Referer"] = f'https://{fuzzing_headers["Referer"]}'

**Comment by tonoitp** [comment]
syntax error pointing at the last character (closing quote)

**Comment by mazen160** [comment]
Hi @tonoitp 

This error happens on Python 2 environments. It should not be reproduced in Python 3 versions.

**Comment by tonoitp** [comment]
ran it with python3 but was an old deb9 server. okay after upgrade to deb10
