### ISSUE TITLE
[Discussion]: Provide a 'headers-minimal.txt' file

### ISSUE THREAD

**Issue by axel3rd** [fullhunt/log4j-scan#83]
In usage of this (⭐ so nice ⭐) scanner, I remark that many security appliance (firewall, ...) refuse any requests which have more 50 headers.

So the **68 defaults** headers of [headers.txt](https://github.com/fullhunt/log4j-scan/blob/master/headers.txt) (70 lines, but 1 blank line & double `X-Api-Version`)

I don't know if this value (50) is a ~default for many network security solutions, but having a `headers-minimal.txt` could be relevant.

It remains to find the ~20 headers which can be removed safely (which not reduce too much the surface attack).

**Comment by mazen160** [comment]
Hi @axel3rd,

Thank you! This is an excellent idea, we should have a minimal version to help in targeted scans.
