### ISSUE TITLE
Dependency issue Crypto / PyCryptodome on Windows

### ISSUE THREAD

**Issue by eyrinck** [fullhunt/log4j-scan#87]
Thanks for your script.
At first on Win 10 I had the dependency issue mentioned in your FAQ:
ModuleNotFoundError: No module named 'Crypto'

Solved it successfully with the method from PyCryptodome FAQ:
pip uninstall crypto
pip uninstall pycryptodome
pip install pycryptodome

Hope this helps other users.

**Comment by raphson93** [comment]
This helps.

`$ pip3 install -r requirements.txt`

**Comment by locklocklock** [comment]
Another solution：
1. Locate your python directory
2. Go to .\Lib\site-packages
3. find crypto folder，rename “Crypto”

**Comment by mazen160** [comment]
Happy to hear it worked eventually!
