### ISSUE TITLE
scan error

### ISSUE THREAD

**Issue by suqianstone** [fullhunt/log4j-scan#97]
python log4j-scan.py -u http://xxx.xxx.xxx/xxx/main.do
  File "log4j-scan.py", line 148
    fuzzing_headers["Referer"] = f'https://{fuzzing_headers["Referer"]}'
                                                                       ^
SyntaxError: invalid syntax

**Comment by axel3rd** [comment]
Duplicate #27 & #79.
Probable Python2 usage.
Python 3 should be used.
